### ISSUE TITLE
Video support?

### ISSUE THREAD

**Issue by earithramir** [Shyri/gba-bt-hid#1]
Hi, great project.
I would like to know does this make the device a pure HID input device or will it be able to receive data too, e.g. video sound.
I would like to use it as a replacement for GBA link cable, will that be possible?

**Comment by Shyri** [comment]
Hi @earithramir 
It just acts as a pure HID device so from the other devices it is seen as a generic gamepad. About streaming video and sound from other device to the GBA, this would not be enough. I don't know if that would be even possible. My project uses uart at 115000 baud, maybe you can stream some video at that rate but that should be encoded and compressed and GBA would need to decode it somehow, and that ROM for sure is not going to fit into a 'multibootable' ROM. Other communication modes can reach 2Mbit/s so maybe there's hope I don't know. 

A different thing would be creating a wireless replacement for GBA cable. This is technically possible but this project is not good for that. For that kind of project, I'd say you would need just some simple RF communicator, you would have two data lines (input/ouput) to read and write from and to the GBA on each side. Maybe you'd need some custom way of wrapping information and regenerate the clock signal on each side. Also note, from what I've read, link cable communications are very sensitive to timing, so very fast wireless communications wold be required.

I hope this answers your questions

**Comment by earithramir** [comment]
Hi thank you for taking the time to answer my question and in detail too.
Reason for asking is i'm a big fan of the zelda series on nintendo and currently own a wii and w wii u because the wii u does not support the GBA communication, only as a hid controller. Was hoping to use this project to bring the GBA support to the wii and be able to let go of the Wii (as 95% of the games are fully functional on the Wii U). 

Thanks again!
