### ISSUE TITLE
ESP-IDF version & btstack missing files

### ISSUE THREAD

**Issue by Shadow7369124** [Shyri/gba-bt-hid#2]
Hello,

What version of ESP-IDF are you using ?

I've spent 5 hours trying to "make flash" but I always get errors, mostly concerning the btstack files that are missing.

Thanks by advance

Regards

**Comment by Shyri** [comment]
Hi @Shadow7369124 Could you please paste the log output here to try to understand the problem? Thanks!

**Comment by Shadow7369124** [comment]
Hello,

Thanks for your reply.

I'll post the logs tomorrow if that's fine, error is the include files in the main.c like btstack.h not found and also freertos.

I've managed to run main.c by removing "hc05.c" and "uart.c", just the multiboot part and that worked :)
I had to rename the main function in main.c to "app_main()" tho.

Regards

**Comment by Shyri** [comment]
@Shadow7369124 I realized the esp-idf I was using was a mix of several things result of being working in other different projects. So I tried a clean esp-idf v3.3.2 install and realized it was not compiling and fixed it in dev branch. Using v.3.3.2 and latest btstack master branch it builds with the canges I pushed to dev branch and it flashes correctly to the ESP32. I still need to test it with the GBA. I'll try to test tomorrow and merge it to master and update the readme. Thanks for pointing it out

**Comment by Shadow7369124** [comment]
Great thanks, I'll try that.
Also, could I contact you elsewhere if possible ? Like discord.

**Comment by Shyri** [comment]
@Shadow7369124 I could confirm that setup is working with the GBA. It throws some warnings during compilation but it is fully working. I'm going to merge and update readme and instructions. Most probably I'll also work on make it compatible with esp-idf v4 because I need it for other projects and I don't want to be changing installations every time.

Sure you can find me in Discord shyri#5614

**Comment by Shadow7369124** [comment]
Thanks!
I've added you on dis :)
